spring:
  application:
    name: begginer
  data:
    rest:
      base-path: /api
      default-page-size: 50
  datasource:
    url: jdbc:postgresql:SpringBoot
    username: danilomourelle
    password: oPN5L94wkD389W7rY3MY3
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # show-sql: true
  main:
    banner-mode: off
  security:
    user:
      name: dan
      password: 1234

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace
      springframework:
        security: DEBUG
        jdbc:
          core: INFO
