spring:
  application:
    name: begginer
  data:
    rest:
      base-path: /api
      default-page-size: 50
  datasource:
    url: jdbc:postgresql:SpringBoot
    username: danilomourelle
    password: oPN5L94wkD389W7rY3MY3
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  main:
    banner-mode: off
  security:
    user:
      name: dan
      password: 1234

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: DEBUG
    root: warn
  
application:
  countries: Brazil,France,Germany,India,Mexico,Spain,United States
  languages: Go,JavaScript,Python,Elixir
  systems: Linux,MacOS,Microsoft Windows,Android,iOS